#!/usr/bin/env bash

if [[ $(uname -s) == 'Darwin' ]]; then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

alias gap='git add -p'
alias gpp='git pull --rebase --autostash && git push'
alias gpr='git pull --rebase --autostash'
alias grep='grep --color=auto'
alias gs='git status'
alias ll="ls -lah"
alias la="ls -latrh"
alias nocaps='/usr/bin/setxkbmap -layout us -option ctrl:nocaps'
alias pbc='tmux show-buffer | DISPLAY=:0 xsel -b'
alias vim='nvim'

# Remove local branches whose remotes have been deleted.
alias cleanbranches="git branch -vv | grep ': gone]' | grep -v '\*' | awk '{print \$1}' | xargs -r git branch -D"

# Linux specific
if [[ $(uname -s) == 'Linux' ]]; then
  # This opens the UI file manager.
  alias open='xdg-open'
  # Copy input from stdin into paste buffer.
  alias pbcopy='xclip -sel clip -in'
  alias pbpaste='xclip -o >'
  # Docker Linux
  alias docker="sudo /usr/bin/docker"
fi

# Kubernetes
alias kuebctl='kubectl'
alias k=kubectl

