#!/bin/bash

if [ $(uname -s) == 'Darwin' ]; then
  alias ls="ls -G"
else
  alias ls="ls --color=auto"
fi

alias ll="ls -la"
alias grep='grep --color=auto'
alias nocaps='/usr/bin/setxkbmap -layout us -option ctrl:nocaps'
alias pbc='tmux show-buffer | DISPLAY=:0 xsel -b'
alias tmux='tmux -f $HOME/workspace/oratos-dotfiles/tmux.conf'
